AUS_ENG_CONVERSIONS = [
    # -or -> -our
    (r'\bcolors?\b', 'colour'),
    (r'\bflavors?\b', 'flavour'),
    (r'\bhumors?\b', 'humour'),
    (r'\blabors?\b', 'labour'),
    (r'\bneighbors?\b', 'neighbour'),
    (r'\bsaviors?\b', 'saviour'),
    # -er -> -re
    (r'\bcenters?\b', 'centre'),
    (r'\bliters?\b', 'litre'),
    (r'\bmeters?\b', 'metre'),
    (r'\btheaters?\b', 'theatre'),
    # -ize/-yze -> -ise/-yse
    (r'\banalyze(s)?\b', 'analyse'),
    (r'\banalyzing\b', 'analysing'),
    (r'\bapologize(s)?\b', 'apologise'),
    (r'\bapologizing\b', 'apologising'),
    (r'\borganize(s)?\b', 'organise'),
    (r'\borganizing\b', 'organising'),
    (r'\borganization(s)?\b', 'organisation'),
    (r'\brealize(s)?\b', 'realise'),
    (r'\brealizing\b', 'realising'),
    (r'\brealization(s)?\b', 'realisation'),
    # Misc
    (r'\bdefense\b', 'defence'),   # Singular
    (r'\bdefenses\b', 'defences'), # Explicit plural
    (r'\blicense(s)?\b', 'licence'),  # Assuming noun context
    (r'\bpajamas\b', 'pyjamas'),    # This is typically plural
    (r'\bprogram(s)?\b', 'programme'),
    (r'\bdialog(s)?\b', 'dialogue'),
    (r'\bcatalog(s)?\b', 'catalogue'),
    (r'\bjudgment\b', 'judgement'),
    (r'\bgray\b', 'grey'),
    (r'\bjewelry\b', 'jewellery'),
    (r'\bmaneuver(s)?\b', 'manoeuvre'),
    (r'\bspecialty\b', 'speciality'), # Singular
    (r'\bspecialties\b', 'specialities'), # Explicit plural
    # L-doubling for -ing/-ed (US single 'l', Aus double 'll')
    (r'\btraveling\b', 'travelling'), (r'\btraveled\b', 'travelled'),
    (r'\bmodeling\b', 'modelling'), (r'\bmodeled\b', 'modelled'),
    (r'\bcanceling\b', 'cancelling'), (r'\bcanceled\b', 'cancelled'),
    (r'\bfueling\b', 'fuelling'), (r'\bfueled\b', 'fuelled'),
    (r'\blabeling\b', 'labelling'), (r'\blabeled\b', 'labelled'),
    (r'\bsignaling\b', 'signalling'), (r'\bsignaled\b', 'signalled'),
    (r'\bdialing\b', 'dialling'), (r'\bdialed\b', 'dialled'),
    # -or -> -our (additional)
    (r'\bfavorites?\b', 'favourite'),
    (r'\bhonors?\b', 'honour'),
    # L-doubling (additional/variations)
    (r'\btravelers?\b', 'traveller'), # Noun form
    # Single 'l' vs Double 'll' (AU single, US double)
    (r'\benroll(s)?\b', 'enrol'),
    (r'\benrolling\b', 'enrolling'),
    (r'\benrollment(s)?\b', 'enrolment'),
    (r'\bfulfill(s)?\b', 'fulfil'),
    (r'\bfulfilling\b', 'fulfilling'),
    (r'\bfulfillment(s)?\b', 'fulfilment'),
    (r'\binstalling\b', 'installing'),
    (r'\binstallment(s)?\b', 'instalment'),
    (r'\bwillful(ly)?\b', 'wilful'),
    # Misc (additional)
    (r'\baeroplanes?\b', 'aeroplane'),
    (r'\baluminum\b', 'aluminium'),
    (r'\bcheque(s)?\b', 'cheque'), # US 'check' (money) vs AU 'cheque'
    (r'\bdraft(s)?\b', 'draught'), # e.g., beer, air
    (r'\bgauge(s)?\b', 'gauge'), # Often same, but 'gage' can be US variant
    (r'\bjail(s)?\b', 'gaol'),
    (r'\bmoustache(s)?\b', 'moustache'), # US 'mustache'
    (r'\bplow(s)?\b', 'plough'),
    (r'\bskeptic(s)?\b', 'sceptic'),
    (r'\bskepticism\b', 'scepticism'),
    (r'\btire(s)?\b', 'tyre'), # Vehicle part
    (r'\bcozy\b', 'cosy'),
    (r'\bcozier\b', 'cosier'),
    (r'\bcoziest\b', 'cosiest'),
    (r'\bcozily\b', 'cosily'),
    (r'\bcoziness\b', 'cosiness'),
    (r'\baging\b', 'ageing'),
    (r'\banesthetic(s)?\b', 'anaesthetic'),
    (r'\banesthesia\b', 'anaesthesia'),
    (r'\bencyclopedia(s)?\b', 'encyclopaedia'),
    (r'\bendeavor(s)?\b', 'endeavour'),
    (r'\bfetus(es)?\b', 'foetus'),
    (r'\bglamor(ous)?\b', 'glamour'),
    (r'\bomelet(te)?(s)?\b', 'omelette'),
    (r'\bsulfur\b', 'sulphur'),
    (r'\bvigor\b', 'vigour'),
    (r'\bwhiskey\b', 'whisky'), # Irish/US 'whiskey', Scottish/Can/Aus/Jap 'whisky'
    # -e vs -oe/-ae (often medical/classical)
    (r'\bestrogen(s)?\b', 'oestrogen'),
    (r'\bpediatric(s)?\b', 'paediatric'),
    (r'\bleukemia\b', 'leukaemia'),
    (r'\bhemorrhage(s)?\b', 'haemorrhage'),
    (r'\bdiarrhea\b', 'diarrhoea'),
    (r'\begis\b', 'aegis'), 
    (r'\bcesarean\b', 'caesarean'),
    # Dropping final 'e' before suffix (US) vs retaining (AU/Br)
    (r'\blikable\b', 'likeable'),
    (r'\bsizable\b', 'sizeable'),
    (r'\bunmistakable\b', 'unmistakeable'),
    (r'\babridgment(s)?\b', 'abridgement'),
    (r'\backnowledgment(s)?\b', 'acknowledgement'),
    # -er -> -re (additional examples)
    (r'\bfiber(s)?\b', 'fibre'),
    (r'\bluster\b', 'lustre'),
    (r'\bmeager\b', 'meagre'),
    (r'\bsaber(s)?\b', 'sabre'),
    (r'\bsomber\b', 'sombre'),
    (r'\bspecter(s)?\b', 'spectre'),
    # Misc spelling differences (even more)
    (r'\bmold(s)?\b', 'mould'),
    (r'\bmolding(s)?\b', 'moulding'),
    (r'\bsmolder(s)?\b', 'smoulder'),
    (r'\bsmoldering\b', 'smouldering'),
    (r'\bdisk(s)?\b', 'disc'), # Computer disk/disc
    (r'\behove(s)?\b', 'behoove'), 
    (r'\bpractice\b', 'practise'), # US verb, AU verb (noun is 'practice' in both)
    (r'\bpracticing\b', 'practising'),
    (r'\bton\b', 'tonne'), # Metric tonne
    (r'\bartifact(s)?\b', 'artefact'),
    # From us2gb-dictionary.txt (UK spellings, closely align with Australian)
    # Batch 1
    (r'\baccessorize(s)?\b', 'accessorise'),
    (r'\baccessorized\b', 'accessorised'),
    (r'\baccessorizing\b', 'accessorising'),
    (r'\bacclimatization\b', 'acclimatisation'),
    (r'\bacclimatize(s)?\b', 'acclimatise'),
    (r'\bacclimatized\b', 'acclimatised'),
    (r'\bacclimatizing\b', 'acclimatising'),
    (r'\baccouterments\b', 'accoutrements'),
    (r'\beon(s)?\b', 'aeon'),
    (r'\baerogram(s)?\b', 'aerogramme'),
    # aeroplane/airplane already exists
    (r'\besthete(s)?\b', 'aesthete'),
    (r'\besthetic\b', 'aesthetic'),
    (r'\besthetically\b', 'aesthetically'),
    (r'\besthetics\b', 'aesthetics'),
    (r'\betiology\b', 'aetiology'),
    # ageing/aging already exists
    (r'\baggrandizement\b', 'aggrandisement'),
    (r'\bagonize(s)?\b', 'agonise'),
    (r'\bagonized\b', 'agonised'),
    (r'\bagonizing\b', 'agonising'),
    (r'\bagonizingly\b', 'agonisingly'),
    (r'\balmanac(s)?\b', 'almanack'),
    # aluminum/aluminium already exists
    (r'\bamortizable\b', 'amortisable'),
    (r'\bamortization(s)?\b', 'amortisation'),
    (r'\bamortize(s)?\b', 'amortise'),
    (r'\bamortized\b', 'amortised'),
    (r'\bamortizing\b', 'amortising'),
    (r'\bamphitheater(s)?\b', 'amphitheatre'),
    (r'\banemia\b', 'anaemia'),
    (r'\banemic\b', 'anaemic'),
    # anaesthesia/anesthesia already exists
    # anaesthetic/anesthetic already exists
    (r'\banesthetize(s)?\b', 'anaesthetise'), # also anaesthetize -> anaesthetise
    (r'\banesthetized\b', 'anaesthetised'), # also anaesthetized -> anaesthetised
    (r'\banesthetizing\b', 'anaesthetising'), # also anaesthetizing -> anaesthetising
    (r'\banesthetist(s)?\b', 'anaesthetist'),
    # analog/analogue - dialogue/dialog - catalogue/catalog already exists, but this adds 'analogues'
    (r'\banalogs\b', 'analogues'),
    # analyze/analyse and forms already exists
    (r'\banglicize(s)?\b', 'anglicise'),
    (r'\banglicized\b', 'anglicised'),
    (r'\banglicizing\b', 'anglicising'),
    (r'\bannualized\b', 'annualised'),
    (r'\bantagonize(s)?\b', 'antagonise'),
    (r'\bantagonized\b', 'antagonised'),
    (r'\bantagonizing\b', 'antagonising'),
    # apologize/apologise and forms already exists
    (r'\bappall(s)?\b', 'appal'), # Note: US often 'appall', UK 'appal'
    (r'\bappetizer(s)?\b', 'appetiser'), # Re-adding as primarily spelling
    (r'\bappetizing\b', 'appetising'),
    (r'\bappetizingly\b', 'appetisingly'),
    (r'\barbor(s)?\b', 'arbour'),
    (r'\barcheological\b', 'archaeological'),
    (r'\barcheologically\b', 'archaeologically'),
    (r'\barcheologist(s)?\b', 'archaeologist'),
    (r'\barcheology\b', 'archaeology'),
    (r'\bardor\b', 'ardour'),
    (r'\barmor(s)?\b', 'armour'),
    (r'\barmored\b', 'armoured'),
    (r'\barmorer(s)?\b', 'armourer'),
    (r'\barmories\b', 'armouries'),
    (r'\barmory\b', 'armoury'),
    # artifact/artefact already exists
    # authorize/authorise and forms already exists
    (r'\bax\b', 'axe'),
    (r'\bbackpedaled\b', 'backpedalled'),
    (r'\bbackpedaling\b', 'backpedalling'),
    (r'\bbanister(s)?\b', 'bannister'),
    (r'\bbaptize(s)?\b', 'baptise'),
    (r'\bbaptized\b', 'baptised'),
    (r'\bbaptizing\b', 'baptising'),
    (r'\bbastardize(s)?\b', 'bastardise'),
    (r'\bbastardized\b', 'bastardised'),
    (r'\bbastardizing\b', 'bastardising'),
    (r'\bbattleax\b', 'battleaxe'),
    (r'\bbalk(s)?\b', 'baulk'), # As in hesitate
    (r'\bbalked\b', 'baulked'),
    (r'\bbalking\b', 'baulking'),
    (r'\bbedeviled\b', 'bedevilled'),
    (r'\bbedeviling\b', 'bedevilling'),
    (r'\bbehavior(s)?\b', 'behaviour'),
    (r'\bbehavioral\b', 'behavioural'),
    (r'\bbehaviorism\b', 'behaviourism'),
    (r'\bbehaviorist(s)?\b', 'behaviourist'),
    # behove/behoove already exists
    (r'\bbejeweled\b', 'bejewelled'),
    (r'\bbelabor(s)?\b', 'belabour'),
    (r'\bbelabored\b', 'belaboured'),
    (r'\bbelaboring\b', 'belabouring'),
    (r'\bbeveled\b', 'bevelled'),
    (r'\bbevies\b', 'bevvies'), # Plural of bevy
    (r'\bbevy\b', 'bevvy'), # Informal drink
    (r'\bbiased\b', 'biassed'),
    (r'\bbiasing\b', 'biassing'),
    (r'\bbinging\b', 'bingeing'), # Note: bingeing is common in AuE
    (r'\bbougainvillea(s)?\b', 'bougainvillaea'),
    (r'\bbowdlerize(s)?\b', 'bowdlerise'),
    (r'\bbowdlerized\b', 'bowdlerised'),
    (r'\bbowdlerizing\b', 'bowdlerising'),
    (r'\bbreathalyze(s)?\b', 'breathalyse'),
    (r'\bbreathalyzed\b', 'breathalysed'),
    (r'\bbreathalyzer(s)?\b', 'breathalyser'),
    (r'\bbreathalyzing\b', 'breathalysing'),
    (r'\bbrutalize(s)?\b', 'brutalise'),
    (r'\bbrutalized\b', 'brutalised'),
    (r'\bbrutalizing\b', 'brutalising'),
    (r'\bbusses\b', 'buses'), # Plural of bus, US can be 'busses'
    (r'\bbussing\b', 'busing'), # Verb, US can be 'bussing'
    # caesarean/cesarean already exists (reversed)
    (r'\bcaliber(s)?\b', 'calibre'),
    (r'\bcaliper(s)?\b', 'calliper'),
    (r'\bcalisthenics\b', 'callisthenics'),
    (r'\bcanalize(s)?\b', 'canalise'),
    (r'\bcanalized\b', 'canalised'),
    (r'\bcanalizing\b', 'canalising'),
    (r'\bcancelation(s)?\b', 'cancellation'), # Note: cancellation is common in US too
    # canceled/cancelled already exists
    # canceling/cancelling already exists
    (r'\bcandor\b', 'candour'),
    (r'\bcannibalize(s)?\b', 'cannibalise'),
    (r'\bcannibalized\b', 'cannibalised'),
    (r'\bcannibalizing\b', 'cannibalising'),
    (r'\bcanonize(s)?\b', 'canonise'),
    (r'\bcanonized\b', 'canonised'),
    (r'\bcanonizing\b', 'canonising'),
    (r'\bcapitalize(s)?\b', 'capitalise'),
    (r'\bcapitalized\b', 'capitalised'),
    (r'\bcapitalizing\b', 'capitalising'),
    (r'\bcaramelize(s)?\b', 'caramelise'),
    (r'\bcaramelized\b', 'caramelised'),
    (r'\bcaramelizing\b', 'caramelising'),
    (r'\bcarbonize(s)?\b', 'carbonise'),
    (r'\bcarbonized\b', 'carbonised'),
    (r'\bcarbonizing\b', 'carbonising'),
    (r'\bcaroled\b', 'carolled'),
    (r'\bcaroling\b', 'carolling'),
    # catalog/catalogue and forms already exists
    (r'\bcatalyze(s)?\b', 'catalyse'),
    (r'\bcatalyzed\b', 'catalysed'),
    (r'\bcatalyzing\b', 'catalysing'),
    (r'\bcategorize(s)?\b', 'categorise'),
    (r'\bcategorized\b', 'categorised'),
    (r'\bcategorizing\b', 'categorising'),
    (r'\bcauterize(s)?\b', 'cauterise'),
    (r'\bcauterized\b', 'cauterised'),
    (r'\bcauterizing\b', 'cauterising'),
    (r'\bcaviled\b', 'cavilled'),
    (r'\bcaviling\b', 'cavilling'),
    (r'\bcentigram(s)?\b', 'centigramme'),
    (r'\bcentiliter(s)?\b', 'centilitre'),
    (r'\bcentimeter(s)?\b', 'centimetre'),
    (r'\bcentralize(s)?\b', 'centralise'),
    (r'\bcentralized\b', 'centralised'),
    (r'\bcentralizing\b', 'centralising'),
    # center/centre and forms already exists
    (r'\bcenterfold(s)?\b', 'centrefold'),
    (r'\bcenterpiece(s)?\b', 'centrepiece'),
    (r'\bchanneled\b', 'channelled'),
    (r'\bchanneling\b', 'channelling'),
    (r'\bcharacterize(s)?\b', 'characterise'),
    (r'\bcharacterized\b', 'characterised'),
    (r'\bcharacterizing\b', 'characterising'),
    # check/cheque already exists
    (r'\bcheckbook(s)?\b', 'chequebook'),
    (r'\bcheckered\b', 'chequered'),
    (r'\bchili\b', 'chilli'),
    (r'\bchimera(s)?\b', 'chimaera'),
    (r'\bchiseled\b', 'chiselled'),
    (r'\bchiseling\b', 'chiselling'),
    (r'\bcircularize(s)?\b', 'circularise'),
    (r'\bcircularized\b', 'circularised'),
    (r'\bcircularizing\b', 'circularising'),
    (r'\bcivilize(s)?\b', 'civilise'),
    (r'\bcivilized\b', 'civilised'),
    (r'\bcivilizing\b', 'civilising'),
    (r'\bclamor(s)?\b', 'clamour'),
    (r'\bclamored\b', 'clamoured'),
    (r'\bclamoring\b', 'clamouring'),
    (r'\bclangor\b', 'clangour'),
    (r'\bclarinetist(s)?\b', 'clarinettist'),
    (r'\bcollectivize(s)?\b', 'collectivise'),
    (r'\bcollectivized\b', 'collectivised'),
    (r'\bcollectivizing\b', 'collectivising'),
    (r'\bcolonization\b', 'colonisation'),
    (r'\bcolonize(s)?\b', 'colonise'),
    (r'\bcolonized\b', 'colonised'),
    (r'\bcolonizer(s)?\b', 'coloniser'),
    (r'\bcolonizing\b', 'colonising'),
    # color/colour and forms already exists
    (r'\bcolorant(s)?\b', 'colourant'),
    (r'\bcolorize(s)?\b', 'colourize'),
    (r'\bcolorized\b', 'colourized'),
    (r'\bcolorizing\b', 'colourizing'),
    (r'\bcommercialize(s)?\b', 'commercialise'),
    (r'\bcommercialized\b', 'commercialised'),
    (r'\bcommercializing\b', 'commercialising'),
    (r'\bcompartmentalize(s)?\b', 'compartmentalise'),
    (r'\bcompartmentalized\b', 'compartmentalised'),
    (r'\bcompartmentalizing\b', 'compartmentalising'),
    (r'\bcomputerize(s)?\b', 'computerise'),
    (r'\bcomputerized\b', 'computerised'),
    (r'\bcomputerizing\b', 'computerising'),
    (r'\bconceptualize(s)?\b', 'conceptualise'),
    (r'\bconceptualized\b', 'conceptualised'),
    (r'\bconceptualizing\b', 'conceptualising'),
    (r'\bconnection(s)?\b', 'connexion'), # Less common, but valid BrE/AuE alternate
    (r'\bcontextualize(s)?\b', 'contextualise'),
    (r'\bcontextualized\b', 'contextualised'),
    (r'\bcontextualizing\b', 'contextualising'),
    # cozy/cosy and forms already exists
    (r'\bcouncilor(s)?\b', 'councillor'),
    (r'\bcounseled\b', 'counselled'),
    (r'\bcounseling\b', 'counselling'),
    (r'\bcounselor(s)?\b', 'counsellor'),
    (r'\bcrenelated\b', 'crenellated'),
    (r'\bcriminalize(s)?\b', 'criminalise'),
    (r'\bcriminalized\b', 'criminalised'),
    (r'\bcriminalizing\b', 'criminalising'),
    (r'\bcriticize(s)?\b', 'criticise'),
    (r'\bcriticized\b', 'criticised'),
    (r'\bcriticizing\b', 'criticising'),
    (r'\bcrueler\b', 'crueller'),
    (r'\bcruelest\b', 'cruellest'),
    (r'\bcrystallization\b', 'crystallisation'),
    (r'\bcrystallize(s)?\b', 'crystallise'),
    (r'\bcrystallized\b', 'crystallised'),
    (r'\bcrystallizing\b', 'crystallising'),
    (r'\bcudgeled\b', 'cudgelled'),
    (r'\bcudgeling\b', 'cudgelling'),
    (r'\bcustomize(s)?\b', 'customise'),
    (r'\bcustomized\b', 'customised'),
    (r'\bcustomizing\b', 'customising'),
    (r'\bcipher(s)?\b', 'cypher'), # cypher is alt in AuE
    (r'\bdecentralization\b', 'decentralisation'),
    (r'\bdecentralize(s)?\b', 'decentralise'),
    (r'\bdecentralized\b', 'decentralised'),
    (r'\bdecentralizing\b', 'decentralising'),
    (r'\bdecriminalization\b', 'decriminalisation'),
    (r'\bdecriminalize(s)?\b', 'decriminalise'),
    (r'\bdecriminalized\b', 'decriminalised'),
    (r'\bdecriminalizing\b', 'decriminalising'),
    # defense/defence and forms already exists
    (r'\bdefenseless\b', 'defenceless'),
    (r'\bdehumanization\b', 'dehumanisation'),
    (r'\bdehumanize(s)?\b', 'dehumanise'),
    (r'\bdehumanized\b', 'dehumanised'),
    (r'\bdehumanizing\b', 'dehumanising'),
    (r'\bdemeanor\b', 'demeanour'),
    (r'\bdemilitarization\b', 'demilitarisation'),
    (r'\bdemilitarize(s)?\b', 'demilitarise'),
    (r'\bdemilitarized\b', 'demilitarised'),
    (r'\bdemilitarizing\b', 'demilitarising'),
    (r'\bdemobilization\b', 'demobilisation'),
    (r'\bdemobilize(s)?\b', 'demobilise'),
    (r'\bdemobilized\b', 'demobilised'),
    (r'\bdemobilizing\b', 'demobilising'),
    (r'\bdemocratization\b', 'democratisation'),
    (r'\bdemocratize(s)?\b', 'democratise'),
    (r'\bdemocratized\b', 'democratised'),
    (r'\bdemocratizing\b', 'democratising'),
    (r'\bdemonize(s)?\b', 'demonise'),
    (r'\bdemonized\b', 'demonised'),
    (r'\bdemonizing\b', 'demonising'),
    (r'\bdemoralization\b', 'demoralisation'),
    (r'\bdemoralize(s)?\b', 'demoralise'),
    (r'\bdemoralized\b', 'demoralised'),
    (r'\bdemoralizing\b', 'demoralising'),
    (r'\bdenationalization\b', 'denationalisation'),
    (r'\bdenationalize(s)?\b', 'denationalise'),
    (r'\bdenationalized\b', 'denationalised'),
    (r'\bdenationalizing\b', 'denationalising'),
    (r'\bdeodorize(s)?\b', 'deodorise'),
    (r'\bdeodorized\b', 'deodorised'),
    (r'\bdeodorizing\b', 'deodorising'),
    (r'\bdepersonalize(s)?\b', 'depersonalise'),
    (r'\bdepersonalized\b', 'depersonalised'),
    (r'\bdepersonalizing\b', 'depersonalising'),
    (r'\bdeputize(s)?\b', 'deputise'),
    (r'\bdeputized\b', 'deputised'),
    (r'\bdeputizing\b', 'deputising'),
    (r'\bdesensitization\b', 'desensitisation'),
    (r'\bdesensitize(s)?\b', 'desensitise'),
    (r'\bdesensitized\b', 'desensitised'),
    (r'\bdesensitizing\b', 'desensitising'),
    (r'\bdestabilization\b', 'destabilisation'),
    (r'\bdestabilize(s)?\b', 'destabilise'),
    (r'\bdestabilized\b', 'destabilised'),
    (r'\bdestabilizing\b', 'destabilising'),
    # dialed/dialled and dialing/dialling already exists
    # dialog/dialogue and forms already exists
    # diarrhea/diarrhoea already exists
    (r'\bdigitize(s)?\b', 'digitise'),
    (r'\bdigitized\b', 'digitised'),
    (r'\bdigitizing\b', 'digitising'),
    # disc/disk already exists (reversed: disk (US) -> disc (AU))
    (r'\bdiscolor(s)?\b', 'discolour'),
    (r'\bdiscolored\b', 'discoloured'),
    (r'\bdiscoloring\b', 'discolouring'),
    (r'\bdisemboweled\b', 'disembowelled'),
    (r'\bdisemboweling\b', 'disembowelling'),
    (r'\bdisfavor\b', 'disfavour'),
    (r'\bdisheveled\b', 'dishevelled'),
    (r'\bdishonor(s)?\b', 'dishonour'),
    (r'\bdishonorable\b', 'dishonourable'),
    (r'\bdishonorably\b', 'dishonourably'),
    (r'\bdishonored\b', 'dishonoured'),
    (r'\bdishonoring\b', 'dishonouring'),
    (r'\bdisorganization\b', 'disorganisation'),
    (r'\bdisorganized\b', 'disorganised'),
    (r'\bdistill(s)?\b', 'distil'), # US distill, UK distil
    (r'\bdramatization(s)?\b', 'dramatisation'),
    (r'\bdramatize(s)?\b', 'dramatise'),
    (r'\bdramatized\b', 'dramatised'),
    (r'\bdramatizing\b', 'dramatising'),
    # draft/draught already exists
    (r'\bdraftboard(s)?\b', 'draughtboard'),
    (r'\bdraftier\b', 'draughtier'),
    (r'\bdraftiest\b', 'draughtiest'),
    (r'\bdraftsman\b', 'draughtsman'),
    (r'\bdraftsmanship\b', 'draughtsmanship'),
    (r'\bdraftsmen\b', 'draughtsmen'),
    (r'\bdraftswoman\b', 'draughtswoman'),
    (r'\bdraftswomen\b', 'draughtswomen'),
    (r'\bdrafty\b', 'draughty'),
    (r'\bdriveled\b', 'drivelled'),
    (r'\bdriveling\b', 'drivelling'),
    (r'\bdueled\b', 'duelled'),
    (r'\bdueling\b', 'duelling'),
    (r'\beconomize(s)?\b', 'economise'),
    (r'\beconomized\b', 'economised'),
    (r'\beconomizing\b', 'economising'),
    (r'\bedema\b', 'edoema'), # edoema is a valid, if less common, BrE/AuE spelling
    (r'\beditorialize(s)?\b', 'editorialise'),
    (r'\beditorialized\b', 'editorialised'),
    (r'\beditorializing\b', 'editorialising'),
    (r'\bempathize(s)?\b', 'empathise'),
    (r'\bempathized\b', 'empathised'),
    (r'\bempathizing\b', 'empathising'),
    (r'\bemphasize(s)?\b', 'emphasise'),
    (r'\bemphasized\b', 'emphasised'),
    (r'\bemphasizing\b', 'emphasising'),
    (r'\benameled\b', 'enamelled'),
    (r'\benameling\b', 'enamelling'),
    (r'\benamored\b', 'enamoured'),
    # encyclopedia/encyclopaedia already exists
    (r'\bencyclopedic\b', 'encyclopaedic'),
    # endeavor/endeavour and forms already exists
    (r'\benergize(s)?\b', 'energise'),
    (r'\benergized\b', 'energised'),
    (r'\benergizing\b', 'energising'),
    # enrol/enroll and forms already exists
    (r'\benthral(s)?\b', 'enthral'), # Often US enthrall, UK enthral
    (r'\bepaulet(s)?\b', 'epaulette'),
    (r'\bepicenter(s)?\b', 'epicentre'),
    (r'\bepilog(s)?\b', 'epilogue'),
    (r'\bepitomize(s)?\b', 'epitomise'),
    (r'\bepitomized\b', 'epitomised'),
    (r'\bepitomizing\b', 'epitomising'),
    (r'\bequalization\b', 'equalisation'),
    (r'\bequalize(s)?\b', 'equalise'),
    (r'\bequalized\b', 'equalised'),
    (r'\bequalizer(s)?\b', 'equaliser'),
    (r'\bequalizing\b', 'equalising'),
    (r'\beulogize(s)?\b', 'eulogise'),
    (r'\beulogized\b', 'eulogised'),
    (r'\beulogizing\b', 'eulogising'),
    (r'\bevangelize(s)?\b', 'evangelise'),
    (r'\bevangelized\b', 'evangelised'),
    (r'\bevangelizing\b', 'evangelising'),
    (r'\bexorcize(s)?\b', 'exorcise'),
    (r'\bexorcized\b', 'exorcised'),
    (r'\bexorcizing\b', 'exorcising'),
    (r'\bextemporization\b', 'extemporisation'),
    (r'\bextemporize(s)?\b', 'extemporise'),
    (r'\bextemporized\b', 'extemporised'),
    (r'\bextemporizing\b', 'extemporising'),
    (r'\bexternalization(s)?\b', 'externalisation'),
    (r'\bexternalize(s)?\b', 'externalise'),
    (r'\bexternalized\b', 'externalised'),
    (r'\bexternalizing\b', 'externalising'),
    (r'\bfactorize(s)?\b', 'factorise'),
    (r'\bfactorized\b', 'factorised'),
    (r'\bfactorizing\b', 'factorising'),
    (r'\bfecal\b', 'faecal'),
    (r'\bfeces\b', 'faeces'),
    (r'\bfamiliarization\b', 'familiarisation'),
    (r'\bfamiliarize(s)?\b', 'familiarise'),
    (r'\bfamiliarized\b', 'familiarised'),
    (r'\bfamiliarizing\b', 'familiarising'),
    (r'\bfantasize(s)?\b', 'fantasise'),
    (r'\bfantasized\b', 'fantasised'),
    (r'\bfantasizing\b', 'fantasising'),
    # favor/favour and related (favorite, favoritism) already exists
    (r'\bfavorable\b', 'favourable'),
    (r'\bfavorably\b', 'favourably'),
    (r'\bfeminize(s)?\b', 'feminise'),
    (r'\bfeminized\b', 'feminised'),
    (r'\bfeminizing\b', 'feminising'),
    (r'\bfertilization\b', 'fertilisation'),
    (r'\bfertilize(s)?\b', 'fertilise'),
    (r'\bfertilized\b', 'fertilised'),
    (r'\bfertilizer(s)?\b', 'fertiliser'),
    (r'\bfertilizing\b', 'fertilising'),
    (r'\bfervor\b', 'fervour'),
    # fiber/fibre and forms already exists
    (r'\bfiberglass\b', 'fibreglass'),
    (r'\bfictionalization(s)?\b', 'fictionalisation'),
    (r'\bfictionalize(s)?\b', 'fictionalise'),
    (r'\bfictionalized\b', 'fictionalised'),
    (r'\bfictionalizing\b', 'fictionalising'),
    (r'\bfilet(s)?\b', 'fillet'), # food
    (r'\bfileted\b', 'filleted'),
    (r'\bfileting\b', 'filleting'),
    (r'\bfinalization\b', 'finalisation'),
    (r'\bfinalize(s)?\b', 'finalise'),
    (r'\bfinalized\b', 'finalised'),
    (r'\bfinalizing\b', 'finalising'),
    (r'\bflutist(s)?\b', 'flautist'),
    # flavor/flavour and forms already exists
    (r'\bflavoring(s)?\b', 'flavouring'),
    (r'\bflavorsome\b', 'flavoursome'),
    (r'\bflier\b', 'flyer'), # flyer/flier can be complex, flyer often preferred AuE for person/leaflet
    (r'\bfetal\b', 'foetal'), # foetal is AuE variant
    (r'\bfetid\b', 'foetid'),
    # fetus/foetus already exists
    (r'\bformalization\b', 'formalisation'),
    (r'\bformalize(s)?\b', 'formalise'),
    (r'\bformalized\b', 'formalised'),
    (r'\bformalizing\b', 'formalising'),
    (r'\bfossilization\b', 'fossilisation'),
    (r'\bfossilize(s)?\b', 'fossilise'),
    (r'\bfossilized\b', 'fossilised'),
    (r'\bfossilizing\b', 'fossilising'),
    (r'\bfraternization\b', 'fraternisation'),
    (r'\bfraternize(s)?\b', 'fraternise'),
    (r'\bfraternized\b', 'fraternised'),
    (r'\bfraternizing\b', 'fraternising'),
    # fulfill/fulfil and related already exists
    (r'\bfunneled\b', 'funnelled'),
    (r'\bfunneling\b', 'funnelling'),
    (r'\bgalvanize(s)?\b', 'galvanise'),
    (r'\bgalvanized\b', 'galvanised'),
    (r'\bgalvanizing\b', 'galvanising'),
    (r'\bgamboled\b', 'gambolled'),
    (r'\bgamboling\b', 'gambolling'),
    # gaol/jail and forms already exists
    (r'\bgasses\b', 'gases'), # Plural of gas, US can be 'gasses'
    # gauge/gage already exists
    (r'\bgeneralization(s)?\b', 'generalisation'),
    (r'\bgeneralize(s)?\b', 'generalise'),
    (r'\bgeneralized\b', 'generalised'),
    (r'\bgeneralizing\b', 'generalising'),
    (r'\bghettoize(s)?\b', 'ghettoise'),
    (r'\bghettoized\b', 'ghettoised'),
    (r'\bghettoizing\b', 'ghettoising'),
    (r'\bgypsies\b', 'gipsies'), # gipsies is alt AuE
    (r'\bglamorize(s)?\b', 'glamorise'),
    (r'\bglamorized\b', 'glamorised'),
    (r'\bglamorizing\b', 'glamorising'),
    # glamour/glamor already exists
    (r'\bglobalization\b', 'globalisation'),
    (r'\bglobalize(s)?\b', 'globalise'),
    (r'\bglobalized\b', 'globalised'),
    (r'\bglobalizing\b', 'globalising'),
    (r'\bgluing\b', 'glueing'), # glueing is alt AuE
    (r'\bgoiter(s)?\b', 'goitre'),
    (r'\bgonorrhea\b', 'gonorrhoea'),
    (r'\bgram(s)?\b', 'gramme'), # for unit of mass
    (r'\bgraveled\b', 'gravelled'),
    # gray/grey and forms already exists
    (r'\bgroveled\b', 'grovelled'),
    (r'\bgroveling\b', 'grovelling'),
    (r'\bgroin(s)?\b', 'groyne'), # structure in water
    (r'\bgrueling\b', 'gruelling'),
    (r'\bgruelingly\b', 'gruellingly'),
    (r'\bgriffin(s)?\b', 'gryphon'), # gryphon is alt AuE
    (r'\bgynecological\b', 'gynaecological'),
    (r'\bgynecologist(s)?\b', 'gynaecologist'),
    (r'\bgynecology\b', 'gynaecology'),
    (r'\bhematological\b', 'haematological'),
    (r'\bhematologist(s)?\b', 'haematologist'),
    (r'\bhematology\b', 'haematology'),
    (r'\bhemoglobin\b', 'haemoglobin'),
    (r'\bhemophilia\b', 'haemophilia'),
    (r'\bhemophiliac(s)?\b', 'haemophiliac'),
    # hemorrhage/haemorrhage and forms already exists
    (r'\bhemorrhoids\b', 'haemorrhoids'),
    (r'\bharbor(s)?\b', 'harbour'),
    (r'\bharbored\b', 'harboured'),
    (r'\bharboring\b', 'harbouring'),
    (r'\bharmonization\b', 'harmonisation'),
    (r'\bharmonize(s)?\b', 'harmonise'),
    (r'\bharmonized\b', 'harmonised'),
    (r'\bharmonizing\b', 'harmonising'),
    (r'\bhomeopath(s)?\b', 'homoeopath'),
    (r'\bhomeopathic\b', 'homoeopathic'),
    (r'\bhomeopathy\b', 'homoeopathy'),
    (r'\bhomogenize(s)?\b', 'homogenise'),
    (r'\bhomogenized\b', 'homogenised'),
    (r'\bhomogenizing\b', 'homogenising'),
    # honor/honour and forms already exists
    (r'\bhospitalization\b', 'hospitalisation'),
    (r'\bhospitalize(s)?\b', 'hospitalise'),
    (r'\bhospitalized\b', 'hospitalised'),
    (r'\bhospitalizing\b', 'hospitalising'),
    (r'\bhumanize(s)?\b', 'humanise'),
    (r'\bhumanized\b', 'humanised'),
    (r'\bhumanizing\b', 'humanising'),
    # humor/humour and forms already exists
    (r'\bhumorless\b', 'humourless'),
    (r'\bhybridize(s)?\b', 'hybridise'),
    (r'\bhybridized\b', 'hybridised'),
    (r'\bhybridizing\b', 'hybridising'),
    (r'\bhypnotize(s)?\b', 'hypnotise'),
    (r'\bhypnotized\b', 'hypnotised'),
    (r'\bhypnotizing\b', 'hypnotising'),
    (r'\bhypothesize(s)?\b', 'hypothesise'),
    (r'\bhypothesized\b', 'hypothesised'),
    (r'\bhypothesizing\b', 'hypothesising'),
    (r'\bidealization\b', 'idealisation'),
    (r'\bidealize(s)?\b', 'idealise'),
    (r'\bidealized\b', 'idealised'),
    (r'\bidealizing\b', 'idealising'),
    (r'\bidolize(s)?\b', 'idolise'),
    (r'\bidolized\b', 'idolised'),
    (r'\bidolizing\b', 'idolising'),
    (r'\bimmobilization\b', 'immobilisation'),
    (r'\bimmobilize(s)?\b', 'immobilise'),
    (r'\bimmobilized\b', 'immobilised'),
    (r'\bimmobilizer(s)?\b', 'immobiliser'),
    (r'\bimmobilizing\b', 'immobilising'),
    (r'\bimmortalize(s)?\b', 'immortalise'),
    (r'\bimmortalized\b', 'immortalised'),
    (r'\bimmortalizing\b', 'immortalising'),
    (r'\bimmunization\b', 'immunisation'),
    (r'\bimmunize(s)?\b', 'immunise'),
    (r'\bimmunized\b', 'immunised'),
    (r'\bimmunizing\b', 'immunising'),
    (r'\bimpaneled\b', 'impanelled'),
    (r'\bimpaneling\b', 'impanelling'),
    (r'\bimperiled\b', 'imperilled'),
    (r'\bimperiling\b', 'imperilling'),
    (r'\bindividualize(s)?\b', 'individualise'),
    (r'\bindividualized\b', 'individualised'),
    (r'\bindividualizing\b', 'individualising'),
    (r'\bindustrialize(s)?\b', 'industrialise'),
    (r'\bindustrialized\b', 'industrialised'),
    (r'\bindustrializing\b', 'industrialising'),
    (r'\binflection(s)?\b', 'inflexion'), # inflexion is alt AuE
    (r'\binitialize(s)?\b', 'initialise'),
    (r'\binitialized\b', 'initialised'),
    (r'\binitializing\b', 'initialising'),
    (r'\binitialed\b', 'initialled'),
    (r'\binitialing\b', 'initialling'),
    # instal/install and forms already exists (instalment/installment)
    (r'\binstill(s)?\b', 'instil'), # US instill, UK instil
    (r'\binstitutionalization\b', 'institutionalisation'),
    (r'\binstitutionalize(s)?\b', 'institutionalise'),
    (r'\binstitutionalized\b', 'institutionalised'),
    (r'\binstitutionalizing\b', 'institutionalising'),
    (r'\bintellectualize(s)?\b', 'intellectualise'),
    (r'\bintellectualized\b', 'intellectualised'),
    (r'\bintellectualizing\b', 'intellectualising'),
    (r'\binternalization\b', 'internalisation'),
    (r'\binternalize(s)?\b', 'internalise'),
    (r'\binternalized\b', 'internalised'),
    (r'\binternalizing\b', 'internalising'),
    (r'\binternationalization\b', 'internationalisation'),
    (r'\binternationalize(s)?\b', 'internationalise'),
    (r'\binternationalized\b', 'internationalised'),
    (r'\binternationalizing\b', 'internationalising'),
    (r'\bionization\b', 'ionisation'),
    (r'\bionize(s)?\b', 'ionise'),
    (r'\bionized\b', 'ionised'),
    (r'\bionizer(s)?\b', 'ioniser'),
    (r'\bionizing\b', 'ionising'),
    (r'\bitalicize(s)?\b', 'italicise'),
    (r'\bitalicized\b', 'italicised'),
    (r'\bitalicizing\b', 'italicising'),
    (r'\bitemize(s)?\b', 'itemise'),
    (r'\bitemized\b', 'itemised'),
    (r'\bitemizing\b', 'itemising'),
    (r'\bjeopardize(s)?\b', 'jeopardise'),
    (r'\bjeopardized\b', 'jeopardised'),
    (r'\bjeopardizing\b', 'jeopardising'),
    (r'\bjeweled\b', 'jewelled'),
    (r'\bjeweler(s)?\b', 'jeweller'),
    # jewelry/jewellery already exists
    # judgment/judgement already exists
    (r'\bkilogram(s)?\b', 'kilogramme'),
    (r'\bkilometer(s)?\b', 'kilometre'),
    # labeled/labelled and labeling/labelling already exists
    # labor/labour and forms already exists
    (r'\blackluster\b', 'lacklustre'),
    (r'\blegalization\b', 'legalisation'),
    (r'\blegalize(s)?\b', 'legalise'),
    (r'\blegalized\b', 'legalised'),
    (r'\blegalizing\b', 'legalising'),
    (r'\blegitimize(s)?\b', 'legitimise'),
    (r'\blegitimized\b', 'legitimised'),
    (r'\blegitimizing\b', 'legitimising'),
    # leukemia/leukaemia already exists
    (r'\bleveled\b', 'levelled'),
    (r'\bleveler(s)?\b', 'leveller'),
    (r'\bleveling\b', 'levelling'),
    (r'\blibeled\b', 'libelled'),
    (r'\blibeling\b', 'libelling'),
    (r'\blibelous\b', 'libellous'),
    (r'\bliberalization\b', 'liberalisation'),
    (r'\bliberalize(s)?\b', 'liberalise'),
    (r'\bliberalized\b', 'liberalised'),
    (r'\bliberalizing\b', 'liberalising'),
    # license/licence already exists
    (r'\blicensed\b', 'licenced'), # verb form can be licenced in BrE/AuE
    (r'\blicensing\b', 'licencing'), # gerund/participle
    # likeable/likable already exists (reversed: likable (US) -> likeable (AU))
    (r'\blionization\b', 'lionisation'),
    (r'\blionize(s)?\b', 'lionise'),
    (r'\blionized\b', 'lionised'),
    (r'\blionizing\b', 'lionising'),
    (r'\bliquidize(s)?\b', 'liquidise'),
    (r'\bliquidized\b', 'liquidised'),
    (r'\bliquidizer(s)?\b', 'liquidiser'),
    (r'\bliquidizing\b', 'liquidising'),
    # liter/litre already exists
    (r'\blocalize(s)?\b', 'localise'),
    (r'\blocalized\b', 'localised'),
    (r'\blocalizing\b', 'localising'),
    (r'\blouver(s)?\b', 'louvre'),
    (r'\blouvered\b', 'louvred'),
    # lustre/luster already exists (reversed: luster (US) -> lustre (AU))
    (r'\bmagnetize(s)?\b', 'magnetise'),
    (r'\bmagnetized\b', 'magnetised'),
    (r'\bmagnetizing\b', 'magnetising'),
    (r'\bmaneuverability\b', 'manoeuvrability'),
    (r'\bmaneuverable\b', 'manoeuvrable'),
    # maneuver/manoeuvre and forms already exists
    (r'\bmaneuverings\b', 'manoeuvrings'),
    (r'\bmarginalization\b', 'marginalisation'),
    (r'\bmarginalize(s)?\b', 'marginalise'),
    (r'\bmarginalized\b', 'marginalised'),
    (r'\bmarginalizing\b', 'marginalising'),
    (r'\bmarshaled\b', 'marshalled'),
    (r'\bmarshaling\b', 'marshalling'),
    (r'\bmarveled\b', 'marvelled'),
    (r'\bmarveling\b', 'marvelling'),
    (r'\bmarvelous\b', 'marvellous'),
    (r'\bmarvelously\b', 'marvellously'),
    (r'\bmaterialization\b', 'materialisation'),
    (r'\bmaterialize(s)?\b', 'materialise'),
    (r'\bmaterialized\b', 'materialised'),
    (r'\bmaterializing\b', 'materialising'),
    (r'\bmaximization\b', 'maximisation'),
    (r'\bmaximize(s)?\b', 'maximise'),
    (r'\bmaximized\b', 'maximised'),
    (r'\bmaximizing\b', 'maximising'),
    # meager/meagre already exists
    (r'\bmechanization\b', 'mechanisation'),
    (r'\bmechanize(s)?\b', 'mechanise'),
    (r'\bmechanized\b', 'mechanised'),
    (r'\bmechanizing\b', 'mechanising'),
    (r'\bmedieval\b', 'mediaeval'), # mediaeval is alt AuE
    (r'\bmemorialize(s)?\b', 'memorialise'),
    (r'\bmemorialized\b', 'memorialised'),
    (r'\bmemorializing\b', 'memorialising'),
    (r'\bmemorize(s)?\b', 'memorise'),
    (r'\bmemorized\b', 'memorised'),
    (r'\bmemorizing\b', 'memorising'),
    (r'\bmesmerize(s)?\b', 'mesmerise'),
    (r'\bmesmerized\b', 'mesmerised'),
    (r'\bmesmerizing\b', 'mesmerising'),
    (r'\bmetabolize(s)?\b', 'metabolise'),
    (r'\bmetabolized\b', 'metabolised'),
    (r'\bmetabolizing\b', 'metabolising'),
    # meter/metre already exists
    (r'\bmicrometer(s)?\b', 'micrometre'),
    (r'\bmilitarize(s)?\b', 'militarise'),
    (r'\bmilitarized\b', 'militarised'),
    (r'\bmilitarizing\b', 'militarising'),
    (r'\bmilligram(s)?\b', 'milligramme'),
    (r'\bmilliliter(s)?\b', 'millilitre'),
    (r'\bmillimeter(s)?\b', 'millimetre'),
    (r'\bminiaturization\b', 'miniaturisation'),
    (r'\bminiaturize(s)?\b', 'miniaturise'),
    (r'\bminiaturized\b', 'miniaturised'),
    (r'\bminiaturizing\b', 'miniaturising'),
    (r'\bminibusses\b', 'minibuses'), # minibuses preferred in AuE
    (r'\bminimize(s)?\b', 'minimise'),
    (r'\bminimized\b', 'minimised'),
    (r'\bminimizing\b', 'minimising'),
    (r'\bmisbehavior\b', 'misbehaviour'),
    (r'\bmisdemeanor(s)?\b', 'misdemeanour'),
    (r'\bmisspelled\b', 'misspelt'), # misspelt common in AuE
    (r'\bmiter(s)?\b', 'mitre'),
    (r'\bmobilization\b', 'mobilisation'),
    (r'\bmobilize(s)?\b', 'mobilise'),
    (r'\bmobilized\b', 'mobilised'),
    (r'\bmobilizing\b', 'mobilising'),
    # modeled/modelled and modeling/modelling already exists
    (r'\bmodeler(s)?\b', 'modeller'),
    (r'\bmodernize(s)?\b', 'modernise'),
    (r'\bmodernized\b', 'modernised'),
    (r'\bmodernizing\b', 'modernising'),
    (r'\bmoisturize(s)?\b', 'moisturise'),
    (r'\bmoisturized\b', 'moisturised'),
    (r'\bmoisturizer(s)?\b', 'moisturiser'),
    (r'\bmoisturizing\b', 'moisturising'),
    (r'\bmonolog(s)?\b', 'monologue'),
    (r'\bmonopolization\b', 'monopolisation'),
    (r'\bmonopolize(s)?\b', 'monopolise'),
    (r'\bmonopolized\b', 'monopolised'),
    (r'\bmonopolizing\b', 'monopolising'),
    (r'\bmoralize(s)?\b', 'moralise'),
    (r'\bmoralized\b', 'moralised'),
    (r'\bmoralizing\b', 'moralising'),
    (r'\bmotorized\b', 'motorised'),
    # mold/mould and related forms already exists
    (r'\bmoldy\b', 'mouldy'),
    (r'\bmolt(s)?\b', 'moult'),
    (r'\bmolted\b', 'moulted'),
    (r'\bmolting\b', 'moulting'),
    # mustache/moustache and related forms already exists
    (r'\bmulticolored\b', 'multicoloured'),
    (r'\bnationalization(s)?\b', 'nationalisation'),
    (r'\bnationalize(s)?\b', 'nationalise'),
    (r'\bnationalized\b', 'nationalised'),
    (r'\bnationalizing\b', 'nationalising'),
    (r'\bnaturalization\b', 'naturalisation'),
    (r'\bnaturalize(s)?\b', 'naturalise'),
    (r'\bnaturalized\b', 'naturalised'),
    (r'\bnaturalizing\b', 'naturalising'),
    # neighbor/neighbour and related forms already exists
    (r'\bneighborliness\b', 'neighbourliness'),
    (r'\bneighborly\b', 'neighbourly'),
    (r'\bneutralization\b', 'neutralisation'),
    (r'\bneutralize(s)?\b', 'neutralise'),
    (r'\bneutralized\b', 'neutralised'),
    (r'\bneutralizing\b', 'neutralising'),
    (r'\bnormalization\b', 'normalisation'),
    (r'\bnormalize(s)?\b', 'normalise'),
    (r'\bnormalized\b', 'normalised'),
    (r'\bnormalizing\b', 'normalising'),
    (r'\bodor(s)?\b', 'odour'),
    (r'\bodorless\b', 'odourless'),
    (r'\besophagus\b', 'oesophagus'), # AuE oesophagus
    (r'\besophaguses\b', 'oesophaguses'), # Plural
    # oestrogen/estrogen already exists (reversed: estrogen (US) -> oestrogen (AU))
    # offense/offence already exists
    # omelet/omelette already exists
    (r'\boptimize(s)?\b', 'optimise'),
    (r'\boptimized\b', 'optimised'),
    (r'\boptimizing\b', 'optimising'),
    # organization/organisation and related forms already exists
    (r'\borganizer(s)?\b', 'organiser'),
    (r'\borthopedic\b', 'orthopaedic'),
    (r'\borthopedics\b', 'orthopaedics'),
    (r'\bostracize(s)?\b', 'ostracise'),
    (r'\bostracized\b', 'ostracised'),
    (r'\bostracizing\b', 'ostracising'),
    (r'\boutmaneuver(s)?\b', 'outmanoeuvre'),
    (r'\boutmaneuvered\b', 'outmanoeuvred'),
    (r'\boutmaneuvering\b', 'outmanoeuvring'),
    (r'\boveremphasize(s)?\b', 'overemphasise'),
    (r'\boveremphasized\b', 'overemphasised'),
    (r'\boveremphasizing\b', 'overemphasising'),
    (r'\boxidization\b', 'oxidisation'),
    (r'\boxidize(s)?\b', 'oxidise'),
    (r'\boxidized\b', 'oxidised'),
    (r'\boxidizing\b', 'oxidising'),
    (r'\bpederast(s)?\b', 'paederast'),
    # pediatric/paediatric and related already exists
    (r'\bpedophile(s)?\b', 'paedophile'),
    (r'\bpedophilia\b', 'paedophilia'),
    (r'\bpaleolithic\b', 'palaeolithic'),
    (r'\bpaleontologist(s)?\b', 'palaeontologist'),
    (r'\bpaleontology\b', 'palaeontology'),
    (r'\bpaneled\b', 'panelled'),
    (r'\bpaneling\b', 'panelling'),
    (r'\bpanelist(s)?\b', 'panellist'),
    (r'\bparalyze(s)?\b', 'paralyse'),
    (r'\bparalyzed\b', 'paralysed'),
    (r'\bparalyzing\b', 'paralysing'),
    (r'\bparceled\b', 'parcelled'),
    (r'\bparceling\b', 'parcelling'),
    (r'\bparlor(s)?\b', 'parlour'),
    (r'\bparticularize(s)?\b', 'particularise'),
    (r'\bparticularized\b', 'particularised'),
    (r'\bparticularizing\b', 'particularising'),
    (r'\bpassivization\b', 'passivisation'),
    (r'\bpassivize(s)?\b', 'passivise'),
    (r'\bpassivized\b', 'passivised'),
    (r'\bpassivizing\b', 'passivising'),
    (r'\bpasteurization\b', 'pasteurisation'),
    (r'\bpasteurize(s)?\b', 'pasteurise'),
    (r'\bpasteurized\b', 'pasteurised'),
    (r'\bpasteurizing\b', 'pasteurising'),
    (r'\bpatronize(s)?\b', 'patronise'),
    (r'\bpatronized\b', 'patronised'),
    (r'\bpatronizing\b', 'patronising'),
    (r'\bpatronizingly\b', 'patronisingly'),
    (r'\bpedaled\b', 'pedalled'),
    (r'\bpedaling\b', 'pedalling'),
    (r'\bpedestrianization\b', 'pedestrianisation'),
    (r'\bpedestrianize(s)?\b', 'pedestrianise'),
    (r'\bpedestrianized\b', 'pedestrianised'),
    (r'\bpedestrianizing\b', 'pedestrianising'),
    (r'\bpenalize(s)?\b', 'penalise'),
    (r'\bpenalized\b', 'penalised'),
    (r'\bpenalizing\b', 'penalising'),
    (r'\bpenciled\b', 'pencilled'),
    (r'\bpenciling\b', 'pencilling'),
    (r'\bpersonalize(s)?\b', 'personalise'),
    (r'\bpersonalized\b', 'personalised'),
    (r'\bpersonalizing\b', 'personalising'),
    (r'\bpharmacopeia(s)?\b', 'pharmacopoeia'),
    (r'\bphilosophize(s)?\b', 'philosophise'),
    (r'\bphilosophized\b', 'philosophised'),
    (r'\bphilosophizing\b', 'philosophising'),
    (r'\bfilter(s)?\b', 'philtre'), # philtre (love potion) is BrE/AuE
    (r'\bphony\b', 'phoney'), # phoney is AuE variant
    (r'\bplagiarize(s)?\b', 'plagiarise'),
    (r'\bplagiarized\b', 'plagiarised'),
    (r'\bplagiarizing\b', 'plagiarising'),
    # plow/plough and forms already exists
    (r'\bplowshare(s)?\b', 'ploughshare'),
    (r'\bpolarization\b', 'polarisation'),
    (r'\bpolarize(s)?\b', 'polarise'),
    (r'\bpolarized\b', 'polarised'),
    (r'\bpolarizing\b', 'polarising'),
    (r'\bpoliticization\b', 'politicisation'),
    (r'\bpoliticize(s)?\b', 'politicise'),
    (r'\bpoliticized\b', 'politicised'),
    (r'\bpoliticizing\b', 'politicising'),
    (r'\bpopularization\b', 'popularisation'),
    (r'\bpopularize(s)?\b', 'popularise'),
    (r'\bpopularized\b', 'popularised'),
    (r'\bpopularizing\b', 'popularising'),
    (r'\bpouf(s)?\b', 'pouffe'), # furniture
    # practice/practise distinction already exists
    (r'\bpresidium(s)?\b', 'praesidium'), # praesidium is alt AuE spelling
    (r'\bpressurization\b', 'pressurisation'),
    (r'\bpressurize(s)?\b', 'pressurise'),
    (r'\bpressurized\b', 'pressurised'),
    (r'\bpressurizing\b', 'pressurising'),
    (r'\bpretense(s)?\b', 'pretence'),
    (r'\bprimeval\b', 'primaeval'), # primaeval is alt AuE spelling
    (r'\bprioritization\b', 'prioritisation'),
    (r'\bprioritize(s)?\b', 'prioritise'),
    (r'\bprioritized\b', 'prioritised'),
    (r'\bprioritizing\b', 'prioritising'),
    (r'\bprivatization(s)?\b', 'privatisation'),
    (r'\bprivatize(s)?\b', 'privatise'),
    (r'\bprivatized\b', 'privatised'),
    (r'\bprivatizing\b', 'privatising'),
    (r'\bprofessionalization\b', 'professionalisation'),
    (r'\bprofessionalize(s)?\b', 'professionalise'),
    (r'\bprofessionalized\b', 'professionalised'),
    (r'\bprofessionalizing\b', 'professionalising'),
    # program/programme already exists (careful with context: computer program is 'program' in AuE)
    (r'\bprolog(s)?\b', 'prologue'),
    (r'\bpropagandize(s)?\b', 'propagandise'),
    (r'\bpropagandized\b', 'propagandised'),
    (r'\bpropagandizing\b', 'propagandising'),
    (r'\bproselytize(s)?\b', 'proselytise'),
    (r'\bproselytized\b', 'proselytised'),
    (r'\bproselytizer(s)?\b', 'proselytiser'),
    (r'\bproselytizing\b', 'proselytising'),
    (r'\bpsychoanalyze(s)?\b', 'psychoanalyse'),
    (r'\bpsychoanalyzed\b', 'psychoanalysed'),
    (r'\bpsychoanalyzing\b', 'psychoanalysing'),
    (r'\bpublicize(s)?\b', 'publicise'),
    (r'\bpublicized\b', 'publicised'),
    (r'\bpublicizing\b', 'publicising'),
    (r'\bpulverization\b', 'pulverisation'),
    (r'\bpulverize(s)?\b', 'pulverise'),
    (r'\bpulverized\b', 'pulverised'),
    (r'\bpulverizing\b', 'pulverising'),
    (r'\bpummel(led)?\b', 'pummelled'), # US pummel, UK pummelled (pummel (US) -> pummelled (AU))
    (r'\bpummeled\b', 'pummelling'), # US pummelling, UK pummelling (pummeled (US) -> pummelling (AU))
    # pajama/pyjama already exists
    (r'\bpizzazz\b', 'pzazz'), # pzazz is alt AuE spelling
    (r'\bquarreled\b', 'quarrelled'),
    (r'\bquarreling\b', 'quarrelling'),
    (r'\bradicalize(s)?\b', 'radicalise'),
    (r'\bradicalized\b', 'radicalised'),
    (r'\bradicalizing\b', 'radicalising'),
    (r'\brancor\b', 'rancour'),
    (r'\brandomize(s)?\b', 'randomise'),
    (r'\brandomized\b', 'randomised'),
    (r'\brandomizing\b', 'randomising'),
    (r'\brationalization(s)?\b', 'rationalisation'),
    (r'\brationalize(s)?\b', 'rationalise'),
    (r'\brationalized\b', 'rationalised'),
    (r'\brationalizing\b', 'rationalising'),
    (r'\braveled\b', 'ravelled'),
    (r'\braveling\b', 'ravelling'),
    (r'\brealizable\b', 'realisable'),
    # realization/realisation and forms already exists
    (r'\brecognizable\b', 'recognisable'),
    (r'\brecognizably\b', 'recognisably'),
    (r'\brecognizance\b', 'recognisance'),
    (r'\brecognize(s)?\b', 'recognise'),
    (r'\brecognized\b', 'recognised'),
    (r'\brecognizing\b', 'recognising'),
    (r'\breconnoiter(s)?\b', 'reconnoitre'),
    (r'\breconnoitered\b', 'reconnoitred'),
    (r'\breconnoitering\b', 'reconnoitring'),
    # refueled/refuelled and refueling/refuelling already exists
    (r'\bregularization\b', 'regularisation'),
    (r'\bregularize(s)?\b', 'regularise'),
    (r'\bregularized\b', 'regularised'),
    (r'\bregularizing\b', 'regularising'),
    (r'\bremodeled\b', 'remodelled'),
    (r'\bremodeling\b', 'remodelling'),
    (r'\bremold(s)?\b', 'remould'),
    (r'\bremolded\b', 'remoulded'),
    (r'\bremolding\b', 'remoulding'),
    (r'\breorganization(s)?\b', 'reorganisation'),
    (r'\breorganize(s)?\b', 'reorganise'),
    (r'\breorganized\b', 'reorganised'),
    (r'\breorganizing\b', 'reorganising'),
    (r'\breveled\b', 'revelled'),
    (r'\breveler(s)?\b', 'reveller'),
    (r'\breveling\b', 'revelling'),
    (r'\brevitalize(s)?\b', 'revitalise'),
    (r'\brevitalized\b', 'revitalised'),
    (r'\brevitalizing\b', 'revitalising'),
    (r'\brevolutionize(s)?\b', 'revolutionise'),
    (r'\brevolutionized\b', 'revolutionised'),
    (r'\brevolutionizing\b', 'revolutionising'),
    (r'\brhapsodize(s)?\b', 'rhapsodise'),
    (r'\brhapsodized\b', 'rhapsodised'),
    (r'\brhapsodizing\b', 'rhapsodising'),
    (r'\brigor(s)?\b', 'rigour'),
    (r'\britualized\b', 'ritualised'),
    (r'\brivaled\b', 'rivalled'),
    (r'\brivaling\b', 'rivalling'),
    (r'\bromanticize(s)?\b', 'romanticise'),
    (r'\bromanticized\b', 'romanticised'),
    (r'\bromanticizing\b', 'romanticising'),
    (r'\brumor(s)?\b', 'rumour'),
    (r'\brumored\b', 'rumoured'),
    # sabre/saber already exists (reversed: saber (US) -> sabre (AU))
    (r'\bsaltpeter\b', 'saltpetre'),
    (r'\bsanitize(s)?\b', 'sanitise'),
    (r'\bsanitized\b', 'sanitised'),
    (r'\bsanitizing\b', 'sanitising'),
    (r'\bsatirize(s)?\b', 'satirise'),
    (r'\bsatirized\b', 'satirised'),
    (r'\bsatirizing\b', 'satirising'),
    # savior/saviour already exists
    (r'\bsavor(s)?\b', 'savour'),
    (r'\bsavored\b', 'savoured'),
    (r'\bsavories\b', 'savouries'),
    (r'\bsavoring\b', 'savouring'),
    (r'\bsavory\b', 'savoury'),
    (r'\bscandalize(s)?\b', 'scandalise'),
    (r'\bscandalized\b', 'scandalised'),
    (r'\bscandalizing\b', 'scandalising'),
    # skeptic/sceptic and related already exists
    (r'\bscepter(s)?\b', 'sceptre'),
    (r'\bscrutinize(s)?\b', 'scrutinise'),
    (r'\bscrutinized\b', 'scrutinised'),
    (r'\bscrutinizing\b', 'scrutinising'),
    (r'\bsecularization\b', 'secularisation'),
    (r'\bsecularize(s)?\b', 'secularise'),
    (r'\bsecularized\b', 'secularised'),
    (r'\bsecularizing\b', 'secularising'),
    (r'\bsensationalize(s)?\b', 'sensationalise'),
    (r'\bsensationalized\b', 'sensationalised'),
    (r'\bsensationalizing\b', 'sensationalising'),
    (r'\bsensitize(s)?\b', 'sensitise'),
    (r'\bsensitized\b', 'sensitised'),
    (r'\bsensitizing\b', 'sensitising'),
    (r'\bsentimentalize(s)?\b', 'sentimentalise'),
    (r'\bsentimentalized\b', 'sentimentalised'),
    (r'\bsentimentalizing\b', 'sentimentalising'),
    (r'\bsepulcher(s)?\b', 'sepulchre'),
    (r'\bserialization(s)?\b', 'serialisation'),
    (r'\bserialize(s)?\b', 'serialise'),
    (r'\bserialized\b', 'serialised'),
    (r'\bserializing\b', 'serialising'),
    (r'\bsermonize(s)?\b', 'sermonise'),
    (r'\bsermonized\b', 'sermonised'),
    (r'\bsermonizing\b', 'sermonising'),
    (r'\bsheik\b', 'sheikh'), # sheikh is common in AuE
    (r'\bshoveled\b', 'shovelled'),
    (r'\bshoveling\b', 'shovelling'),
    (r'\bshriveled\b', 'shrivelled'),
    (r'\bshriveling\b', 'shrivelling'),
    (r'\bsignalize(s)?\b', 'signalise'), # Less common than signal
    (r'\bsignalized\b', 'signalised'),
    (r'\bsignalizing\b', 'signalising'),
    # signaled/signalled and signaling/signalling already exists
    # smolder/smoulder and forms already exists
    (r'\bsniveled\b', 'snivelled'),
    (r'\bsniveling\b', 'snivelling'),
    (r'\bsnorkeled\b', 'snorkelled'),
    (r'\bsnorkeling\b', 'snorkelling'),
    (r'\bsnowplow(s)?\b', 'snowplough'),
    (r'\bsocialization\b', 'socialisation'),
    (r'\bsocialize(s)?\b', 'socialise'),
    (r'\bsocialized\b', 'socialised'),
    (r'\bsocializing\b', 'socialising'),
    (r'\bsodomize(s)?\b', 'sodomise'),
    (r'\bsodomized\b', 'sodomised'),
    (r'\bsodomizing\b', 'sodomising'),
    (r'\bsolemnize(s)?\b', 'solemnise'),
    (r'\bsolemnized\b', 'solemnised'),
    (r'\bsolemnizing\b', 'solemnising'),
    # somber/sombre already exists
    (r'\bspecialization(s)?\b', 'specialisation'),
    (r'\bspecialize(s)?\b', 'specialise'),
    (r'\bspecialized\b', 'specialised'),
    (r'\bspecializing\b', 'specialising'),
    # specter/spectre already exists
    (r'\bspiraled\b', 'spiralled'),
    (r'\bspiraling\b', 'spiralling'),
    (r'\bsplendor(s)?\b', 'splendour'),
    (r'\bsquirreled\b', 'squirrelled'),
    (r'\bsquirreling\b', 'squirrelling'),
    (r'\bstabilization\b', 'stabilisation'),
    (r'\bstabilize(s)?\b', 'stabilise'),
    (r'\bstabilized\b', 'stabilised'),
    (r'\bstabilizer(s)?\b', 'stabiliser'),
    (r'\bstabilizing\b', 'stabilising'),
    (r'\bstandardization\b', 'standardisation'),
    (r'\bstandardize(s)?\b', 'standardise'),
    (r'\bstandardized\b', 'standardised'),
    (r'\bstandardizing\b', 'standardising'),
    (r'\bstenciled\b', 'stencilled'),
    (r'\bstenciling\b', 'stencilling'),
    (r'\bsterilization(s)?\b', 'sterilisation'),
    (r'\bsterilize(s)?\b', 'sterilise'),
    (r'\bsterilized\b', 'sterilised'),
    (r'\bsterilizer(s)?\b', 'steriliser'),
    (r'\bsterilizing\b', 'sterilising'),
    (r'\bstigmatization\b', 'stigmatisation'),
    (r'\bstigmatize(s)?\b', 'stigmatise'),
    (r'\bstigmatized\b', 'stigmatised'),
    (r'\bstigmatizing\b', 'stigmatising'),
    (r'\bstory\b', 'storey'), # floor of a building
    (r'\bstories\b', 'storeys'), # plural floors of a building
    (r'\bsubsidization\b', 'subsidisation'),
    (r'\bsubsidize(s)?\b', 'subsidise'),
    (r'\bsubsidized\b', 'subsidised'),
    (r'\bsubsidizer(s)?\b', 'subsidiser'),
    (r'\bsubsidizing\b', 'subsidising'),
    (r'\bsuccor(s)?\b', 'succour'),
    (r'\bsuccored\b', 'succoured'),
    (r'\bsuccoring\b', 'succouring'),
    (r'\bsulfate(s)?\b', 'sulphate'),
    (r'\bsulfide(s)?\b', 'sulphide'),
    # sulfur/sulphur already exists
    (r'\bsulfurous\b', 'sulphurous'),
    (r'\bsummarize(s)?\b', 'summarise'),
    (r'\bsummarized\b', 'summarised'),
    (r'\bsummarizing\b', 'summarising'),
    (r'\bswiveled\b', 'swivelled'),
    (r'\bswiveling\b', 'swivelling'),
    (r'\bsymbolize(s)?\b', 'symbolise'),
    (r'\bsymbolized\b', 'symbolised'),
    (r'\bsymbolizing\b', 'symbolising'),
    (r'\bsympathize(s)?\b', 'sympathise'),
    (r'\bsympathized\b', 'sympathised'),
    (r'\bsympathizer(s)?\b', 'sympathiser'),
    (r'\bsympathizing\b', 'sympathising'),
    (r'\bsynchronization\b', 'synchronisation'),
    (r'\bsynchronize(s)?\b', 'synchronise'),
    (r'\bsynchronized\b', 'synchronised'),
    (r'\bsynchronizing\b', 'synchronising'),
    (r'\bsynthesize(s)?\b', 'synthesise'),
    (r'\bsynthesized\b', 'synthesised'),
    (r'\bsynthesizer(s)?\b', 'synthesiser'),
    (r'\bsynthesizing\b', 'synthesising'),
    (r'\bsiphon(s)?\b', 'syphon'), # syphon is alt AuE
    (r'\bsiphoned\b', 'syphoned'),
    (r'\bsiphoning\b', 'syphoning'),
    (r'\bsystematization\b', 'systematisation'),
    (r'\bsystematize(s)?\b', 'systematise'),
    (r'\bsystematized\b', 'systematised'),
    (r'\bsystematizing\b', 'systematising'),
    (r'\btantalize(s)?\b', 'tantalise'),
    (r'\btantalized\b', 'tantalised'),
    (r'\btantalizing\b', 'tantalising'),
    (r'\btantalizingly\b', 'tantalisingly'),
    (r'\btasseled\b', 'tasselled'),
    (r'\btechnicolor\b', 'technicolour'),
    (r'\btemporize(s)?\b', 'temporise'),
    (r'\btemporized\b', 'temporised'),
    (r'\btemporizing\b', 'temporising'),
    (r'\btenderize(s)?\b', 'tenderise'),
    (r'\btenderized\b', 'tenderised'),
    (r'\btenderizing\b', 'tenderising'),
    (r'\bterrorize(s)?\b', 'terrorise'),
    (r'\bterrorized\b', 'terrorised'),
    (r'\bterrorizing\b', 'terrorising'),
    # theater/theatre already exists
    (r'\btheatergoer(s)?\b', 'theatregoer'),
    (r'\btheorize(s)?\b', 'theorise'),
    (r'\btheorized\b', 'theorised'),
    (r'\btheorizing\b', 'theorising'),
    # ton/tonne already exists
    (r'\btoweled\b', 'towelled'),
    (r'\btoweling\b', 'towelling'),
    (r'\btoxemia\b', 'toxaemia'), # toxaemia is AuE
    (r'\btranquilize(s)?\b', 'tranquillise'), # also tranquilize -> tranquillise
    (r'\btranquilized\b', 'tranquillised'), # also tranquilized -> tranquillised
    (r'\btranquilizer(s)?\b', 'tranquilliser'), # also tranquilizer -> tranquilliser
    (r'\btranquilizing\b', 'tranquillising'), # also tranquilizing -> tranquillising
    (r'\btranquility\b', 'tranquillity'), # AuE tranquillity
    (r'\btransistorized\b', 'transistorised'),
    (r'\btraumatize(s)?\b', 'traumatise'),
    (r'\btraumatized\b', 'traumatised'),
    (r'\btraumatizing\b', 'traumatising'),
    # traveled/travelled, traveler/traveller, traveling/travelling already exists
    (r'\btravelog(s)?\b', 'travelogue'),
    (r'\btrialed\b', 'trialled'), # AuE often trialled
    (r'\btrialing\b', 'trialling'), # AuE often trialling
    (r'\btricolor(s)?\b', 'tricolour'),
    (r'\btrivialize(s)?\b', 'trivialise'),
    (r'\btrivialized\b', 'trivialised'),
    (r'\btrivializing\b', 'trivialising'),
    (r'\btumor(s)?\b', 'tumour'),
    (r'\btunneled\b', 'tunnelled'),
    (r'\btunneling\b', 'tunnelling'),
    (r'\btyrannize(s)?\b', 'tyrannise'),
    (r'\btyrannized\b', 'tyrannised'),
    (r'\btyrannizing\b', 'tyrannising'),
    # tire/tyre already exists
    (r'\bunauthorized\b', 'unauthorised'),
    (r'\buncivilized\b', 'uncivilised'),
    (r'\bunderutilized\b', 'underutilised'),
    (r'\bunequaled\b', 'unequalled'), # AuE often unequalled
    (r'\bunfavorable\b', 'unfavourable'),
    (r'\bunfavorably\b', 'unfavourably'),
    (r'\bunionization\b', 'unionisation'),
    (r'\bunionize(s)?\b', 'unionise'),
    (r'\bunionized\b', 'unionised'),
    (r'\bunionizing\b', 'unionising'),
    (r'\bunorganized\b', 'unorganised'),
    (r'\bunraveled\b', 'unravelled'),
    (r'\bunraveling\b', 'unravelling'),
    (r'\bunrecognizable\b', 'unrecognisable'),
    (r'\bunrecognized\b', 'unrecognised'),
    (r'\bunrivaled\b', 'unrivalled'), # AuE often unrivalled
    (r'\bunsavory\b', 'unsavoury'),
    (r'\buntrammeled\b', 'untrammelled'), # AuE often untrammelled
    (r'\burbanization\b', 'urbanisation'),
    (r'\burbanize(s)?\b', 'urbanise'),
    (r'\burbanized\b', 'urbanised'),
    (r'\burbanizing\b', 'urbanising'),
    (r'\butilizable\b', 'utilisable'),
    (r'\butilization\b', 'utilisation'),
    (r'\butilize(s)?\b', 'utilise'),
    (r'\butilized\b', 'utilised'),
    (r'\butilizing\b', 'utilising'),
    (r'\bvalor\b', 'valour'),
    (r'\bvandalize(s)?\b', 'vandalise'),
    (r'\bvandalized\b', 'vandalised'),
    (r'\bvandalizing\b', 'vandalising'),
    (r'\bvaporization\b', 'vaporisation'),
    (r'\bvaporize(s)?\b', 'vaporise'),
    (r'\bvaporized\b', 'vaporised'),
    (r'\bvaporizing\b', 'vaporising'),
    (r'\bvapor(s)?\b', 'vapour'),
    (r'\bverbalize(s)?\b', 'verbalise'),
    (r'\bverbalized\b', 'verbalised'),
    (r'\bverbalizing\b', 'verbalising'),
    (r'\bvictimization\b', 'victimisation'),
    (r'\bvictimize(s)?\b', 'victimise'),
    (r'\bvictimized\b', 'victimised'),
    (r'\bvictimizing\b', 'victimising'),
    (r'\bvideodisk(s)?\b', 'videodisc'), # videodisc is AuE
    # vigor/vigour already exists
    (r'\bvisualization(s)?\b', 'visualisation'),
    (r'\bvisualize(s)?\b', 'visualise'),
    (r'\bvisualized\b', 'visualised'),
    (r'\bvisualizing\b', 'visualising'),
    (r'\bvocalization(s)?\b', 'vocalisation'),
    (r'\bvocalize(s)?\b', 'vocalise'),
    (r'\bvocalized\b', 'vocalised'),
    (r'\bvocalizing\b', 'vocalising'),
    (r'\bvulcanized\b', 'vulcanised'),
    (r'\bvulgarization\b', 'vulgarisation'),
    (r'\bvulgarize(s)?\b', 'vulgarise'),
    (r'\bvulgarized\b', 'vulgarised'),
    (r'\bvulgarizing\b', 'vulgarising'),
    (r'\bwagon(s)?\b', 'waggon'), # waggon is alt AuE
    (r'\bwatercolor(s)?\b', 'watercolour'),
    (r'\bweaseled\b', 'weaselled'),
    (r'\bweaseling\b', 'weaselling'),
    (r'\bwesternization\b', 'westernisation'),
    (r'\bwesternize(s)?\b', 'westernise'),
    (r'\bwesternized\b', 'westernised'),
    (r'\bwesternizing\b', 'westernising'),
    (r'\bwomanize(s)?\b', 'womanise'),
    (r'\bwomanized\b', 'womanised'),
    (r'\bwomanizer(s)?\b', 'womaniser'),
    (r'\bwomanizing\b', 'womanising'),
    (r'\bwoolen(s)?\b', 'woollen'),
    (r'\bwoolies\b', 'woollies'), # plural of woolly
    (r'\bwooly\b', 'woolly'),
    (r'\bworshiped\b', 'worshipped'), # AuE worshipped
    (r'\bworshiping\b', 'worshipping'), # AuE worshipping
    (r'\bworshiper\b', 'worshipper'), # AuE worshipper
    (r'\byodeled\b', 'yodelled'),
    (r'\byodeling\b', 'yodelling'),
    (r'\byogurt(s)?\b', 'yoghourt'), # yoghourt is alt BrE/AuE, also yoghurt
    (r'\byogurt(s)?\b', 'yoghurt') # yoghurt is common AuE
] 